name: Azure CLI 09
on: workflow_dispatch


permissions:
      id-token: write
      contents: read
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: acitons checkout
        uses: actions/checkout@v1
      - name: Azure CLI RG
        uses: Azure/cli@v1
        with:
          inlineScript: |
                         chmod +x $GITHUB_WORKSPACE/AZ-CLI-scripts/session-09/az-group.sh
                         $GITHUB_WORKSPACE/AZ-CLI-scripts/session-09/az-group.sh MyRgGroup   
      - name: Azure CLI storage acc
        uses: Azure/cli@v1
        with:
          inlineScript: |
                         chmod +x $GITHUB_WORKSPACE/AZ-CLI-scripts/session-09/storage-acc.sh
                         $GITHUB_WORKSPACE/AZ-CLI-scripts/session-09/storage-acc.sh MyRgGroup   
      - name: Azure CLI backup
        uses: Azure/cli@v1
        with:
          inlineScript: |
                         chmod +x $GITHUB_WORKSPACE/AZ-CLI-scripts/session-09/backups-app-acc.sh
                         $GITHUB_WORKSPACE/AZ-CLI-scripts/session-09/backups-app-acc.sh MyRgGroup  
      - name: Azure CLI delete resourcec
        uses: Azure/cli@v1
        with:
          inlineScript: |
                         chmod +x $GITHUB_WORKSPACE/AZ-CLI-scripts/session-09/delete_all.sh
                         $GITHUB_WORKSPACE/AZ-CLI-scripts/session-09/delete_all.sh MyRgGroup
